### PR TITLE
[fix]: Fix optional chaining bug in img-redundant-alt rule

### LINKED ISSUE #794: img-redundant-alt warning cannot handle optional chaining operator
Hello.

I encountered an odd situation recently with `jsx-a11y/img-redundant-alt`, whereby I had an `img` tag like so:

```js
<img src={imageSource?.url} alt={imgSource?.name} />
```

And this triggered the warning. If I remove the `?.` from the value of `alt` and use just `.`, the warning goes away. That is:

```js
<img src={imageSource?.url} alt={imgSource.name} />
```

The above code snippet doesn't trigger the warning.

### PR DESCRIPTION
**Pull request by uncommon-type**
## Description

This PR fixes an optional chaining bug in the ``img-redundant-alt`` rule. It adds valid test cases with optional chaining operator to the ``img-redundant-alt-test`` file and makes sure they have a ``parserOptions`` property for configuring parser behaviour. Along with that, it adds ``semver@6`` to ensure that tests using optional chaining skip eslint < 6

## Related Issue

Closes #794  

## Acceptance Criteria

- [x] Add test cases with optional chaining operator
- [x] Add parserOptions prop to each test case to configure parser behaviour
- [x] Add semver to tests using optional chaining to ensure they skip eslint < 6

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
| ✓ | :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### CODE REVIEW

File: __tests__/src/rules/img-redundant-alt-test.js [hunk 1]
```diff
@@ -28,7 +30,8 @@ const expectedError = {
 };
 
 ruleTester.run('img-redundant-alt', rule, {
-  valid: [
+  valid: semver.satisfies(eslintVersion, '>= 6') ? [{ code: '<img alt={imageAlt?.name} />', parserOptions: { ecmaVersion: 2020 } },
+    { code: '<img alt="Doing cool things" aria-hidden={foo?.bar}/>', parserOptions: { ecmaVersion: 2020 } }].map(parserOptionsMapper) : [
     { code: '<img alt="foo" />;' },
     { code: '<img alt="picture of me taking a photo of an image" aria-hidden />' },
     { code: '<img aria-hidden alt="photo of image" />' },
```
Comment (ljharb) [inline __tests__/src/rules/img-redundant-alt-test.js:37]:
```suggestion
  valid: [].concat(
    { code: '<img alt="foo" />;' },
    { code: '<img alt="picture of me taking a photo of an image" aria-hidden />' },
    { code: '<img aria-hidden alt="photo of image" />' },
```

File: __tests__/src/rules/img-redundant-alt-test.js [hunk 2]
```diff
@@ -55,8 +58,6 @@ ruleTester.run('img-redundant-alt', rule, {
     { code: '<img alt />' },
     { code: '<img alt={imageAlt} />' },
     { code: '<img alt={imageAlt.name} />' },
-    { code: '<img alt={imageAlt?.name} />', parserOptions: { ecmaVersion: 2020 } },
-    { code: '<img alt="Doing cool things" aria-hidden={foo?.bar}/>', parserOptions: { ecmaVersion: 2020 } },
     { code: '<img alt="Photography" />;' },
     { code: '<img alt="ImageMagick" />;' },
   ].map(parserOptionsMapper),
```
Comment (ljharb) [inline __tests__/src/rules/img-redundant-alt-test.js:63]:
```suggestion
    semver.satisfies(eslintVersion, '>= 6') ? [
      { code: '<img alt={imageAlt?.name} />', parserOptions: { ecmaVersion: 2020 } },
      { code: '<img alt="Doing cool things" aria-hidden={foo?.bar}/>', parserOptions: { ecmaVersion: 2020 } },
    ] : [],
    { code: '<img alt="Photography" />;' },
    { code: '<img alt="ImageMagick" />;' },
  ).map(parserOptionsMapper),
```

File: package.json [hunk 3]
```diff
@@ -73,7 +73,8 @@
     "has": "^1.0.3",
     "jsx-ast-utils": "^3.2.1",
     "language-tags": "^1.0.5",
-    "minimatch": "^3.0.5"
+    "minimatch": "^3.0.5",
+    "semver": "^7.3.5"
```
Comment (ljharb) [inline package.json:77]: this needs to be semver 6, since semver 7 requires node 10.

**Review by ljharb — CHANGES_REQUESTED** [review]

**Review by ljharb — APPROVED** [review]
Looks great! Will land once tests pass.
